language: python
python:
  - 3.5
env:
  - GUNICORN_WORKS=1
  - PORT=5005
  - DB_DATA_BASE=base_site
  - DB_USER=root
  - DB_PASSWORD=example
  - DB_HOST=db
  - DB_PORT=3306
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls