# Generated by Django 2.0.4 on 2018-05-01 16:56

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelexample',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='modelexample',
            name='title',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='modelexample',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='Crop Image'),
        ),
        migrations.AlterField(
            model_name='modelexample',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploaded_images', verbose_name='Image'),
        ),
    ]
